name: build-and-archive-angular-app
on: [push]
jobs:
  build-test:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout repository
      uses: "actions/checkout@v2"
    - name: Setup Node-Environment
      uses: "actions/setup-node@v2"
      with:
        node-version: '18'
    - name: Build optimized web application
      run: |
        npm ci
        npm run build --prod
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
